Pricing Components
pcl-labs/BrowTricks pull request #566
Opened 2021-05-01 16:17 UTC by giteshk11

# Issue Being Addressed
#565 

Put the issue(s) # that your PR is addressing here. e.g. `#15`, `#29`

# Type of PR

Put an `x` in the brackets for the type(s) of PR this is. You may tick more than one.

- [ ] Bug Fix
- [ ] Refactor
- [x] New Feature
- [x] Update to Existing Feature
- [ ] Other (state below)

# Description
- Created Account Manage Page with new routes
- Created components for pricing 
- Refactor existing components

# How to Test/Reproduce

Provide steps on how one can test your changes here. e.g.
1. Login into the app
2. Click on Account from the bottom navigation
3. Click on settings (gear icon) from the top right corner.
4. Click on the Manage Account option.
5. Click on Upgrade to Pro to see the bottom slider

# Screenshots/casts

![localhost_8080_wait_signup=1 token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9 eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjU3OSIsImV4cCI6MTYyMjQ3NzU4MCwiaXNzIjoic3R (2)](https://user-images.githubusercontent.com/17675390/116788361-bad99400-aac6-11eb-9f86-5bcb26a3c0da.png)
![localhost_8080_wait_signup=1 token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9 eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjU3OSIsImV4cCI6MTYyMjQ3NzU4MCwiaXNzIjoic3R (1)](https://user-images.githubusercontent.com/17675390/116788362-bca35780-aac6-11eb-89eb-a378a4297386.png)
![localhost_8080_wait_signup=1 token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9 eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjU3OSIsImV4cCI6MTYyMjQ3NzU4MCwiaXNzIjoic3RhZ2l](https://user-images.githubusercontent.com/17675390/116788363-bd3bee00-aac6-11eb-8e64-fe48211f761c.png)
![localhost_8080_wait_signup=1 token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9 eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjU3OSIsImV4cCI6MTYyMjQ3NzU4MCwiaXNzIjoic3R (3)](https://user-images.githubusercontent.com/17675390/116788364-bdd48480-aac6-11eb-9ccb-b15468d60eeb.png)

# Additional Context

Provide any additional notes that you think would help effective review of your code.

2021-05-01 18:00 UTC, atharva3010 requested changes
Minor code quality changes, but apart from that good job!

2021-05-01 18:00 UTC, atharva3010 commented on src/components/ExpansionPanel.vue
> +            :class="headingColor"
Can bind static and dynamic classes together, for eg:
```
:class="[headingColor, 'title mr-4 text-opacity-high min-w-expansion-panel text-left tg-body-bold-mobile']"
```

2021-05-01 18:01 UTC, atharva3010 commented
@bamboochow haven't tested out the UI, I'll leave that to you.

2021-05-01 18:14 UTC, bamboochow commented
@giteshk11 

# Spelling 
"Standard" is spelled wrong here 
![image](https://user-images.githubusercontent.com/14948326/116791267-0ff5b580-aa87-11eb-87fa-41ca612c3b07.png)

# Text Styling 
Top text should be H3 in Champagne and Limousines font 
Card Titles should be H2 in Champagne and Limousines font  
![image](https://user-images.githubusercontent.com/14948326/116791306-5d722280-aa87-11eb-8b16-6d08a087789b.png)

2021-05-02 04:40 UTC, atharva3010 approved these changes

2021-05-02 04:59 UTC, merged