Subscription Flow UI
pcl-labs/BrowTricks pull request #574
Opened 2021-05-09 19:04 UTC by giteshk11

# Issue Being Addressed

#100 

# Type of PR

Put an `x` in the brackets for the type(s) of PR this is. You may tick more than one.

- [ ] Bug Fix
- [x] Refactor
- [x] New Feature
- [x] Update to Existing Feature
- [ ] Other (state below)

# Description

- Created components for Account Activity layout.
- Created support components for account activity.
- Created Payment Methods Layout.
- Created add new Payment method button.
- Created form for adding card information and billing address (without validations).

# How to Test/Reproduce

Provide steps on how one can test your changes here. e.g.
#### Account Activity 
1. Log in to the account with your account.
2. Click on account from the bottom navigation.
3. Click on the gear icon from the top right side.
4. Click on billing and then activity to see the mockup billing data.
5. Click on any item to see Transaction details.

#### Payment Methods
1. Log in to the account with your account.
2. Click on account from the bottom navigation.
3. Click on the gear icon from the top right side.
4. Click on billing and then payment methods to see the mockup payment methods
5. Click on add payment method button to open form for adding card information and billing address.

2021-05-15 19:17 UTC, atharva3010 requested changes
Looks okayish, minor issues

2021-05-15 19:17 UTC, atharva3010 commented on src/components/paymentMethods/AddCardInfoForm.vue
> +          });
Instead of having the same `this.loadingUpdate(false)` in both then and catch, just use `.finally()`
Also, in case of catch, report the error to rollbar: `Rollbar.error("Couldn't add card info", error);`. It's also important to notify the user about what went wrong, best to use a snackbar for it.

On other note, if you are using async/await, best to use try/catch, instead of mixing then/catch.

2021-05-15 19:17 UTC, atharva3010 commented on src/components/paymentMethods/PaymentMethodCard.vue
> +    }
How will a user know if the action was successful? Notify the user about success/error and report errors to rollbar

2021-05-15 19:17 UTC, atharva3010 commented on src/store/modules/paymentMethod.js
> +    },
Continue the pattern of returning a promise and resolve/reject as you are doing in other actions, to maintain consistency.

2021-05-15 19:17 UTC, atharva3010 commented on src/views/PaymentMethods.vue
> +    >
So, the button will disappear once the user adds a payment method? What if they want to add another method?

2021-05-15 19:17 UTC, atharva3010 commented on src/views/TransactionDetails.vue
> +    </div>
Why is this hardcoded?

2021-05-15 19:17 UTC, atharva3010 commented on vue.config.js
> +    // }
What is this?

2021-05-15 19:17 UTC, atharva3010 commented on vue.config.js
> +
This isn't being used?

2021-05-15 19:31 UTC, atharva3010 commented
Checking the UI, these items should have `cursor-pointer` on them. Default cursor doesn't give the impression that they are clickable. We should also have a hover style perhaps?
![image](https://user-images.githubusercontent.com/34229217/118375889-3caae080-b5e2-11eb-8c69-5b6564ea034e.png)

2021-05-15 19:33 UTC, atharva3010 commented
There should be a button to go back from the Activity section to the page the user came from.

![image](https://user-images.githubusercontent.com/34229217/118375912-6bc15200-b5e2-11eb-8d64-4f553955c429.png)

2021-05-15 19:35 UTC, atharva3010 commented
Clicking on this button doesn't do anything?

![image](https://user-images.githubusercontent.com/34229217/118375949-b80c9200-b5e2-11eb-81a6-af3b74dea447.png)

2021-05-15 19:36 UTC, atharva3010 commented
Noticed a lot of errors in the console when I went to the payment methods page:
![image](https://user-images.githubusercontent.com/34229217/118375988-f30ec580-b5e2-11eb-8f9b-a3b0505d4450.png)

2021-05-15 19:38 UTC, atharva3010 commented
Save and camera buttons are too close, The save button also needs to be distinguishable as a button.

![image](https://user-images.githubusercontent.com/34229217/118376023-1cc7ec80-b5e3-11eb-8102-5bed8cecb4da.png)

2021-05-15 19:40 UTC, atharva3010 commented
Upon clicking save, the user needs to get feedback about what happened.
Need to do two things:
1. Use the loading property of the button to ensure feedback that a request is in process.
2. Show success/error snackbar after request finishes.

Right now there is no feedback whatsoever,
(This errored out btw)
![image](https://user-images.githubusercontent.com/34229217/118376070-631d4b80-b5e3-11eb-81da-d855ef0d9efa.png)

2021-05-16 04:50 UTC, giteshk11 commented on src/views/TransactionDetails.vue
> +    </div>
No API

2021-05-16 04:51 UTC, giteshk11 commented on vue.config.js
> +    // }
> There should be a button to go back from the Activity section to the page the user came from.
> 
> ![image](https://user-images.githubusercontent.com/34229217/118375912-6bc15200-b5e2-11eb-8d64-4f553955c429.png)

There was no button in designs so i didnt add

2021-05-16 04:55 UTC, giteshk11 commented
https://github.com/pcl-labs/BrowTricks/pull/574#issuecomment-841713601
Seems like your browser is blocking stripe request or its the deploy preview.

2021-05-16 05:34 UTC, giteshk11 commented on src/components/paymentMethods/PaymentMethodCard.vue
> +    }
This is not tested yet as API is not working, once the API starts working, i'll fix this

2021-05-16 05:37 UTC, giteshk11 commented
https://github.com/pcl-labs/BrowTricks/pull/574#issuecomment-841713799
I think you might need to clear cache, it looks like this
![localhost_8080_tenant_kaze-226_payment-methods(Moto G4)](https://user-images.githubusercontent.com/17675390/118386673-d0a69780-b636-11eb-831e-9d739de6d90e.png)

2021-05-16 06:06 UTC, giteshk11 commented on src/views/PaymentMethods.vue
> +    >
this button shows up again once you add a payment method button

2021-05-16 14:03 UTC, atharva3010 commented
> [#574 (comment)](https://github.com/pcl-labs/BrowTricks/pull/574#issuecomment-841713799)
> I think you might need to clear cache, it looks like this
> ![localhost_8080_tenant_kaze-226_payment-methods(Moto G4)](https://user-images.githubusercontent.com/17675390/118386673-d0a69780-b636-11eb-831e-9d739de6d90e.png)

Have you tested it in other browsers? There is no issue with cache.

![image](https://user-images.githubusercontent.com/34229217/118400013-8268b700-b67d-11eb-93df-0bcc34847e3d.png)

Also, the save button is clashing with the upload button. Increase margin

2021-05-18 22:57 UTC, bamboochow commented
# UI Consistency 
https://deploy-preview-574--browtricks.netlify.app/tenant/test-salon-193/payment-methods
Is there any way for these 2 sections to remain consistent in design? It looks weird to have 2 different font styles and animations, we can use whatever default it was but we need it to be the same on a single screen
![image](https://user-images.githubusercontent.com/14948326/118732971-6c87fd00-b809-11eb-89ce-04505631188f.png)

#Activity need back button 
https://deploy-preview-574--browtricks.netlify.app/tenant/test-salon-193/activity
![image](https://user-images.githubusercontent.com/14948326/118733270-f637ca80-b809-11eb-93dc-e3f116660008.png)

#Update Standard Card Copy 
https://deploy-preview-574--browtricks.netlify.app/tenant/test-salon-193/manage-account
Update standard card copy of subscription update drawer to this:
![image](https://user-images.githubusercontent.com/14948326/118733664-b2919080-b80a-11eb-9a4b-de6b524870a7.png)

# Saved payment method
Does the card showing a saved payment method exist yet? 
![image](https://user-images.githubusercontent.com/14948326/118733769-ed93c400-b80a-11eb-806b-6f52ad8f9706.png)

2021-05-19 17:18 UTC, bamboochow commented
@StrangeWill 
@giteshk11 mentioned that the delete payment api was not working, what is the status on that?

2021-05-19 17:25 UTC, StrangeWill commented
@bamboochow when was this last reported? We had a bug where our local DB wasn't synced but that has been remedied (to fix the two test records, delete them again).

2021-05-19 17:27 UTC, bamboochow commented
@giteshk11 when was the issue last reported?

2021-05-23 12:57 UTC, atharva3010 commented on src/views/AccountActivity.vue
> +          <IconRectangle />
What does this mean?

2021-05-23 13:01 UTC, giteshk11 commented on src/views/AccountActivity.vue
> +          <IconRectangle />
![image](https://user-images.githubusercontent.com/17675390/119261423-fe6e7c00-bbf4-11eb-9e52-0258b3bfee0f.png)
Talking about this icon, not sure if something will come from the API or it's going to be like this

2021-05-23 14:03 UTC, atharva3010 commented on src/views/AccountActivity.vue
> +          <IconRectangle />
Hmm, alright.

2021-06-14 03:03 UTC, merged